spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=MemphisOrganizationProdDB
    username: 'agentmemphis'
    password: '@g3ntm3mph!s'
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
