spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=MemphisAccountDevDB
    username: '{cipher}38e155217ec7b02ad97f73c83e200d4e4585e2e35e89f218af6246fdac875b5d'
    password: '{cipher}a807dd88ad07d7736d129766ea6b342e02324c8a1cec073b6cf60df8e1a4e3e2'
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
logging:
  level:
    com.rzdp.memphis.account: DEBUG
