spring:
  application:
    name: memphis-account
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=MemphisAccountDevDB
    username: 'agentmemphis'
    password: '@g3ntm3mph!s'
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
