USE MemphisOrganizationDevDB;
-- USE MemphisOrganizationProdDB;


DROP TABLE IF EXISTS organization
DROP TABLE IF EXISTS organization_address
DROP TABLE IF EXISTS organization_contact

CREATE TABLE organization_address (
	id BIGINT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	line1 VARCHAR(150) NOT NULL,
	line2 VARCHAR(150),
	line3 VARCHAR(150),
	city VARCHAR(50) NOT NULL,
	[state] VARCHAR(50) NOT NULL,
	country VARCHAR(50) NOT NULL,
	postal VARCHAR(10) NOT NULL,
	created_by VARCHAR(50) NOT NULL,
	created_date DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	modified_by VARCHAR(50) NOT NULL,
	modified_date DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
)

CREATE TABLE organization_contact (
	id BIGINT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	mobile VARCHAR(10) NOT NULL,
	email VARCHAR(50) NOT NULL,
	tel VARCHAR(8) NULL,
	created_by VARCHAR(50) NOT NULL,
	created_date DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	modified_by VARCHAR(50) NOT NULL,
	modified_date DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
)

CREATE TABLE organization (
	id BIGINT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	address_id BIGINT FOREIGN KEY REFERENCES organization_address (id),
	contact_id BIGINT FOREIGN KEY REFERENCES organization_contact (id),
	[name] VARCHAR(50) NOT NULL,
	domain VARCHAR(100) NOT NULL,
	created_by VARCHAR(50) NOT NULL,
	created_date DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	modified_by VARCHAR(50) NOT NULL,
	modified_date DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
)

INSERT INTO organization_address
VALUES ('303', 'ROXAS ST.', 'SAN. ROQUE, MARIKINA CITY', 'MARIKINA CITY', 'NCR', 'PHILIPPINES', '1800', 'AGENT_MEMPHIS', SYSUTCDATETIME(), 'AGENT_MEMPHIS', SYSUTCDATETIME());

INSERT INTO organization_contact
VALUES ('9304833139', 'hr@fnatic.com', '26556922', 'AGENT_MEMPHIS', SYSUTCDATETIME(), 'AGENT_MEMPHIS', SYSUTCDATETIME());

INSERT INTO organization
VALUES (1, 1, 'Fnatic', 'fnatic.com', 'AGENT_MEMPHIS', SYSUTCDATETIME(), 'AGENT_MEMPHIS', SYSUTCDATETIME());