spring:
  application:
    name: memphis-config-server
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/rzdp/memphis.git
          search-paths:
          - memphis-config/global/
          - memphis-config/memphis-account/
          - memphis-config/memphis-organization/
  profiles:
    active: default
server:
  port: 8888
encrypt:
  key: ${ENCRYPT_KEY}
