CREATE DATABASE MemphisAccountDevDB;
CREATE DATABASE MemphisAccountProdDB;

USE MemphisAccountDevDB;
-- USE MemphisAccountProdDB;

DROP TABLE IF EXISTS account

CREATE TABLE account (
	id BIGINT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	organization_id VARCHAR(10) NOT NULL,
	email VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL,
	phone VARCHAR(10) NOT NULL,
	active BIT NOT NULL DEFAULT 0,
	created_by VARCHAR(50) NOT NULL,
	created_date DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	modified_by VARCHAR(50) NOT NULL,
	modified_date DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
)

INSERT INTO account 
VALUES ('MORG000001', 'sample@domain.com', 'p@ssw0rd', '9304872333', 1, 'AGENT_MEMPHIS', SYSUTCDATETIME(), 'AGENT_MEMPHIS', SYSUTCDATETIME())

SELECT * FROM account